name: agmip
channels:
  - defaults
dependencies:
  - ca-certificates=2021.4.13=hecd8cb5_1
  - certifi=2020.12.5=py37hecd8cb5_0
  - libcxx=10.0.0=1
  - libffi=3.3=hb1e8313_2
  - ncurses=6.2=h0a44026_1
  - openssl=1.1.1k=h9ed2024_0
  - pip=21.1.1=py37hecd8cb5_0
  - python=3.7.7=hf48f09d_4
  - readline=8.1=h9ed2024_0
  - setuptools=52.0.0=py37hecd8cb5_0
  - sqlite=3.35.4=hce871da_0
  - tk=8.6.10=hb0a8c7a_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - appmode==0.5.0
    - appnope==0.1.2
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==21.2.0
    - backcall==0.2.0
    - bleach==3.3.0
    - cffi==1.14.5
    - cycler==0.10.0
    - decorator==5.0.9
    - defusedxml==0.7.1
    - entrypoints==0.3
    - importlib-metadata==4.0.1
    - ipykernel==5.5.5
    - ipython==7.23.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.18.0
    - jinja2==3.0.1
    - jsonschema==3.2.0
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - kiwisolver==1.3.1
    - markupsafe==2.0.1
    - matplotlib==3.2.2
    - matplotlib-inline==0.1.2
    - mistune==0.8.4
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.0
    - numpy==1.20.3
    - packaging==20.9
    - pandas==1.1.0
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.10.1
    - prompt-toolkit==3.0.18
    - ptyprocess==0.7.0
    - pycparser==2.20
    - pygments==2.9.0
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pyzmq==22.0.3
    - send2trash==1.5.0
    - six==1.16.0
    - terminado==0.10.0
    - testpath==0.5.0
    - tornado==6.1
    - traitlets==5.0.5
    - typing-extensions==3.10.0.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==3.4.1
