name: agmip
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - anyio=3.1.0=py37hf985489_0
  - appnope=0.1.2=py37hf985489_1
  - argon2-cffi=20.1.0=py37hf967b71_2
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bleach=3.3.0=pyh44b312d_0
  - brotlipy=0.7.0=py37hf967b71_1001
  - ca-certificates=2021.5.30=h033912b_0
  - certifi=2021.5.30=py37hf985489_0
  - cffi=1.14.5=py37h4d371b4_0
  - chardet=4.0.0=py37hf985489_1
  - cryptography=3.4.7=py37hce4a858_0
  - decorator=5.0.9=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - idna=2.10=pyh9f0ad1d_0
  - ipykernel=5.5.5=py37h85f7c60_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.0=py37hf985489_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py37hf985489_0
  - jupyter_server=1.8.0=pyhd8ed1ab_0
  - jupyterlab=3.0.16=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.6.0=pyhd8ed1ab_0
  - libcxx=10.0.0=1
  - libffi=3.3=hb1e8313_2
  - libsodium=1.0.18=hbcb3906_1
  - markupsafe=2.0.1=py37h271585c_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mistune=0.8.4=py37hf967b71_1003
  - nbclassic=0.3.1=pyhd8ed1ab_1
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py37hf985489_3
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h2e338ed_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - notebook=6.4.0=pyha770c72_0
  - openssl=1.1.1k=h0d85af4_0
  - packaging=20.9=pyh44b312d_0
  - pandoc=2.14.0.1=h0d85af4_0
  - parso=0.8.2=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=21.1.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.18=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.9.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py37hf967b71_2
  - pysocks=1.7.1=py37hf985489_3
  - python=3.7.7=hf48f09d_4
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2021.1=pyhd8ed1ab_0
  - readline=8.1=h05e3726_0
  - requests=2.25.1=pyhd3deb0d_0
  - send2trash=1.5.0=py_0
  - setuptools=52.0.0=py37hecd8cb5_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.2.0=py37hf985489_1
  - sqlite=3.35.4=h44b9ce1_0
  - terminado=0.10.0=py37hf985489_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - tk=8.6.10=h0419947_1
  - tornado=6.1=py37hf967b71_1
  - traitlets=5.0.5=py_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - urllib3=1.26.5=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - websocket-client=0.57.0=py37hf985489_4
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=haf1e3a3_1
  - zeromq=4.3.4=h23ab428_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h7795811_1010
  - pip:
    - appdirs==1.4.4
    - appmode==0.5.0
    - autopep8==1.5.7
    - black==21.5b2
    - click==8.0.1
    - cycler==0.10.0
    - et-xmlfile==1.1.0
    - flake8==3.9.2
    - flake8-mypy==17.8.0
    - flask==2.0.1
    - importlib-metadata==4.0.1
    - iniconfig==1.1.1
    - ipython==7.23.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - itsdangerous==2.0.1
    - kiwisolver==1.3.1
    - matplotlib==3.2.2
    - mccabe==0.6.1
    - mypy==0.812
    - mypy-extensions==0.4.3
    - numpy==1.20.3
    - openpyxl==3.0.7
    - pandas==1.1.0
    - pandocfilters==1.4.3
    - pathspec==0.8.1
    - pluggy==0.13.1
    - prometheus-client==0.10.1
    - py==1.10.0
    - pycodestyle==2.7.0
    - pyflakes==2.3.1
    - pytest==6.2.4
    - pyzmq==22.0.3
    - regex==2021.4.4
    - selenium==3.141.0
    - toml==0.10.2
    - typed-ast==1.4.3
    - webencodings==0.5.1
    - werkzeug==2.0.1
    - widgetsnbextension==3.5.1
